# Generated by Django 2.1.7 on 2019-02-27 10:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mlblogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlblogger_title', models.CharField(max_length=200)),
                ('mlblogger_content', models.TextField()),
                ('mlblogger_published', models.DateTimeField(default=datetime.datetime(2019, 2, 27, 16, 6, 19, 471794), verbose_name='date published')),
                ('mlblogger_slug', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MlbloggerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlblogger_category', models.CharField(max_length=200)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MlbloggerSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlblogger_series', models.CharField(max_length=200)),
                ('series_summary', models.CharField(max_length=200)),
                ('mlblogger_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.MlbloggerCategory', verbose_name='category')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.AddField(
            model_name='mlblogger',
            name='mlblogger_series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.MlbloggerSeries', verbose_name='Series'),
        ),
    ]
