# Generated by Django 2.1.7 on 2019-02-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mlblogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlblogger_title', models.CharField(max_length=200)),
                ('mlblogger_content', models.TextField()),
                ('mlblogger_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
