# Generated by Django 2.1.7 on 2019-02-23 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlblogger',
            name='mlblogger_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 24, 2, 20, 40, 578656), verbose_name='date published'),
        ),
    ]
