# Generated by Django 2.1.7 on 2019-02-23 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190224_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlblogger',
            name='mlblogger_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 24, 3, 16, 21, 717481), verbose_name='date published'),
        ),
    ]
