# Generated by Django 2.1.7 on 2019-02-24 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190224_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlblogger',
            name='mlblogger_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 24, 6, 21, 2, 243458), verbose_name='date published'),
        ),
    ]
