# Generated by Django 2.1.7 on 2019-02-24 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190225_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlblogger',
            name='mlblogger_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 3, 4, 29, 268072), verbose_name='date published'),
        ),
    ]
