# Generated by Django 2.1.7 on 2019-02-24 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190225_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlblogger',
            old_name='mlblogger_series',
            new_name='Mlblog_series',
        ),
        migrations.RenameField(
            model_name='mlblogger',
            old_name='mlblogger_slug',
            new_name='Mlblogger_slug',
        ),
        migrations.RenameField(
            model_name='mlbloggercategory',
            old_name='mlblogger_category',
            new_name='Mlblog_category',
        ),
        migrations.RenameField(
            model_name='mlbloggerseries',
            old_name='mlblogger_category',
            new_name='Mlblog_category',
        ),
        migrations.RenameField(
            model_name='mlbloggerseries',
            old_name='mlblogger_series',
            new_name='Mlblog_series',
        ),
        migrations.AlterField(
            model_name='mlblogger',
            name='mlblogger_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 3, 14, 41, 344389), verbose_name='date published'),
        ),
    ]
