# Generated by Django 2.1.7 on 2019-02-24 21:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190225_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlblogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlblogger_category', models.CharField(max_length=200)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MlblogSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlblogger_series', models.CharField(max_length=200)),
                ('series_summary', models.CharField(max_length=200)),
                ('mlblogger_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.MlblogCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.RemoveField(
            model_name='mlbloggerseries',
            name='Mlblog_category',
        ),
        migrations.RenameField(
            model_name='mlblogger',
            old_name='Mlblogger_slug',
            new_name='mlblogger_slug',
        ),
        migrations.RemoveField(
            model_name='mlblogger',
            name='Mlblog_series',
        ),
        migrations.AlterField(
            model_name='mlblogger',
            name='mlblogger_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 3, 22, 50, 142993), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='MlbloggerCategory',
        ),
        migrations.DeleteModel(
            name='MlbloggerSeries',
        ),
        migrations.AddField(
            model_name='mlblogger',
            name='mlblogger_series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.MlblogSeries', verbose_name='Series'),
        ),
    ]
