# Generated by Django 2.1.7 on 2019-02-24 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190225_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlblogseries',
            name='mlblogger_category',
        ),
        migrations.RemoveField(
            model_name='mlblogger',
            name='mlblogger_series',
        ),
        migrations.RemoveField(
            model_name='mlblogger',
            name='mlblogger_slug',
        ),
        migrations.AlterField(
            model_name='mlblogger',
            name='mlblogger_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 3, 45, 19, 758217), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='MlblogCategory',
        ),
        migrations.DeleteModel(
            name='MlblogSeries',
        ),
    ]
